<a href="https://colab.research.google.com/github/micsung/data_analysis_n_application/blob/main/20211027%E8%B3%87%E6%96%99%E6%8E%A2%E5%8B%98Week7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


In [3]:
%%R
four_seasons <- c("spring", "summer", "autumn", "winter")
four_seasons


[1] "spring" "summer" "autumn" "winter"


In [4]:
%%R
weekends <- c("Saturday", "Sunday")
my_lucky_numbers <- c(7L, 24L)
weekends

[1] "Saturday" "Sunday"  


In [5]:
%%R
four_seasons_factor <- factor(four_seasons)
print(four_seasons_factor)

[1] spring summer autumn winter
Levels: autumn spring summer winter


In [6]:
%%R
four_seasons <- c("spring", "summer", "autumn", "winter")
four_seasons_factor <- factor(four_seasons, ordered = TRUE, levels = c("summer", "winter", "spring", "autumn"))
four_seasons_factor


[1] spring summer autumn winter
Levels: summer < winter < spring < autumn


In [7]:
%%R
temperatures <- c("warm", "hot", "cold")
temp_factors <- factor(temperatures, ordered = TRUE, levels = c("warm", "hot", "cold"))
temp_factors

[1] warm hot  cold
Levels: warm < hot < cold


In [8]:
%%R
temperatures <- c("warm", "hot", "windy")
temp_factors <- factor(temperatures, ordered = TRUE, levels = c("warm","hot","windy"))
temp_factors

[1] warm  hot   windy
Levels: warm < hot < windy


In [9]:
%%R
print(month.name)
for (m in month.name){
   print(m)
}

 [1] "January"   "February"  "March"     "April"     "May"       "June"     
 [7] "July"      "August"    "September" "October"   "November"  "December" 
[1] "January"
[1] "February"
[1] "March"
[1] "April"
[1] "May"
[1] "June"
[1] "July"
[1] "August"
[1] "September"
[1] "October"
[1] "November"
[1] "December"


In [10]:
%%R

print(month.name)


 [1] "January"   "February"  "March"     "April"     "May"       "June"     
 [7] "July"      "August"    "September" "October"   "November"  "December" 


In [11]:
%%R
i <- 6
while (i < 12){
   print(month.name[i])
   i <- i + 1
}

[1] "June"
[1] "July"
[1] "August"
[1] "September"
[1] "October"
[1] "November"


In [ ]:
%%R
flip_results <- c() # 建立一個空的向量來放置每一次投擲的結果
coin <- c(TRUE, FALSE) # TRUE 代表正面，FALSE 代表反面
n_flips <- 1 # 從第一次投擲開始記錄

while (sum(flip_results) < 3){
    flip_results[n_flips] <- sample(coin, size = 1) # 將每次投擲結果記錄起來
    n_flips <- n_flips + 1 # 準備記錄下一次的投擲結果
}
length(flip_results) # 印出每次投擲的紀錄
print(length(flip_results))
print(flip_results)

[1] 4
[1] FALSE  TRUE  TRUE  TRUE


In [12]:
%%R
my_mat <- matrix(1:6, nrow = 2, byrow = TRUE)
print(my_mat)
my_mat[2]

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[1] 4


In [13]:
%%R
my_mat <- matrix(1:6, nrow = 2)
print(my_mat)
filter <- my_mat < 6 | my_mat > 2
my_mat[filter]

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] 1 2 3 4 5 6


In [14]:
%%R
my_mat <- matrix(c(1, 2, TRUE, FALSE, 3, 4), nrow = 2)
my_mat

     [,1] [,2] [,3]
[1,]    1    1    3
[2,]    2    0    4


In [15]:
%%R
team_name <- c("Chicago Bulls", "Golden State Warriors")
wins <- c(72, 73)
losses <- c(10, 9)
is_champion <- c(TRUE, FALSE)
season <- c("1995-96", "2015-16")
great_nba_teams <- data.frame(team_name, wins, losses, is_champion, season)
print(great_nba_teams) # 選出第一個變數的第一個觀測值 "Chicago Bulls"
print(great_nba_teams[, 1])

              team_name wins losses is_champion  season
1         Chicago Bulls   72     10        TRUE 1995-96
2 Golden State Warriors   73      9       FALSE 2015-16
[1] "Chicago Bulls"         "Golden State Warriors"


In [16]:
%%R
team_name <- c("Chicago Bulls", "Golden State Warriors", "Boston Rocket")
wins <- c(72, 73, 69)
losses <- c(10, 9, 10)
is_champion <- c(TRUE, FALSE, TRUE)
season <- c("1995-96", "2015-16", "2008-09")
 
great_nba_teams <- data.frame(team_name, wins, losses, is_champion, season, stringsAsFactors = FALSE)
filter <- great_nba_teams$is_champion == TRUE
great_nba_teams[filter, ] # 注意這個逗號
print(str(great_nba_teams))

'data.frame':	3 obs. of  5 variables:
 $ team_name  : chr  "Chicago Bulls" "Golden State Warriors" "Boston Rocket"
 $ wins       : num  72 73 69
 $ losses     : num  10 9 10
 $ is_champion: logi  TRUE FALSE TRUE
 $ season     : chr  "1995-96" "2015-16" "2008-09"
NULL


In [17]:
%%R
city <- c("Tampa","Seattle","Hartford","Denver")
state <- c("FL","WA","CT","CO")
zipcode <- c(33602,98104,06161,80294)
addresses <- cbind(city,state,zipcode)
#Print a header.
cat("# # # # The First data frame\n")
print(addresses)

# Create another data frame with similar columns
new.address <- data.frame(
   city = c("Lowry","Charlotte"),
   state = c("CO","FL"),
   zipcode = c("80230","33949"),
   stringsAsFactors = FALSE
)

# Print a header.
cat("# # # The Second data frame\n") 

# Print the data frame.
print(new.address)
# Combine rows form both the data frames.
all.addresses <- rbind(addresses,new.address)

# Print a header.
cat("# # # The combined data frame\n") 

# Print the result.
print(all.addresses)

# # # # The First data frame
     city       state zipcode
[1,] "Tampa"    "FL"  "33602"
[2,] "Seattle"  "WA"  "98104"
[3,] "Hartford" "CT"  "6161" 
[4,] "Denver"   "CO"  "80294"
# # # The Second data frame
       city state zipcode
1     Lowry    CO   80230
2 Charlotte    FL   33949
# # # The combined data frame
       city state zipcode
1     Tampa    FL   33602
2   Seattle    WA   98104
3  Hartford    CT    6161
4    Denver    CO   80294
5     Lowry    CO   80230
6 Charlotte    FL   33949


In [19]:
%%R
install.packages("reshape")
library(reshape)
library(MASS)
merged.Pima <- merge(x = Pima.te, y = Pima.tr,
   by.x = c("bp", "bmi"),
   by.y = c("bp", "bmi")
)
print(merged.Pima)
nrow(merged.Pima)


R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

R[write to console]: also installing the dependency ‘plyr’


R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/plyr_1.8.7.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 401481 bytes (392 KB)

R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to consol

   bp  bmi npreg.x glu.x skin.x ped.x age.x type.x npreg.y glu.y skin.y ped.y
1  60 33.8       1   117     23 0.466    27     No       2   125     20 0.088
2  64 29.7       2    75     24 0.370    33     No       2   100     23 0.368
3  64 31.2       5   189     33 0.583    29    Yes       3   158     13 0.295
4  64 33.2       4   117     27 0.230    24     No       1    96     27 0.289
5  66 38.1       3   115     39 0.150    28     No       1   114     36 0.289
6  68 38.5       2   100     25 0.324    26     No       7   129     49 0.439
7  70 27.4       1   116     28 0.204    21     No       0   124     20 0.254
8  70 33.1       4    91     32 0.446    22     No       9   123     44 0.374
9  70 35.4       9   124     33 0.282    34     No       6   134     23 0.542
10 72 25.6       1   157     21 0.123    24     No       4    99     17 0.294
11 72 37.7       5    95     33 0.370    27     No       6   103     32 0.324
12 74 25.9       9   134     33 0.460    81     No       8   126

In [20]:
%%R
library(reshape)

library(MASS)
print(nrow(ships))
molten.ships <- melt(ships, id = c("type","year"))
library(reshape)

library(MASS)
print(ships)
molten.ships <- melt(ships, id = c("type","service"))
print("====")
print(molten.ships)

[1] 40
   type year period service incidents
1     A   60     60     127         0
2     A   60     75      63         0
3     A   65     60    1095         3
4     A   65     75    1095         4
5     A   70     60    1512         6
6     A   70     75    3353        18
7     A   75     60       0         0
8     A   75     75    2244        11
9     B   60     60   44882        39
10    B   60     75   17176        29
11    B   65     60   28609        58
12    B   65     75   20370        53
13    B   70     60    7064        12
14    B   70     75   13099        44
15    B   75     60       0         0
16    B   75     75    7117        18
17    C   60     60    1179         1
18    C   60     75     552         1
19    C   65     60     781         0
20    C   65     75     676         1
21    C   70     60     783         6
22    C   70     75    1948         2
23    C   75     60       0         0
24    C   75     75     274         1
25    D   60     60     251         0
26   

In [21]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


In [22]:
%%R
library(class)

train <- rbind(iris3[1:25,,1], iris3[1:25,,2], iris3[1:25,,3])
#test <- rbind(iris3[26:50,,1], iris3[26:50,,2], iris3[26:50,,3])
test <- c(1.4,1.5,1.4,1.5)
cls <- factor(c(rep("s",25), rep("c",25), rep("v",25)))

summary(knn(train, test, cls, k=25, prob = TRUE))

R[write to console]: 
Attaching package: ‘class’


R[write to console]: The following object is masked from ‘package:reshape’:

    condense




c s v 
0 1 0 
